/**
 * tools/notion/settings-dict.mjs — 「⚙️ 站点设置」的功能说明词典与优先级定义
 *
 * 说明文字是三层拼装出来的（由 notion-settings.mjs 负责组装）：
 *   1. KEY_DESC[完整键路径]     —— 人工词条，针对最常改的键（优先级最高）
 *   2. GROUP_DESC[顶层分组] + LEAF_DESC[末级键名] —— 组装式兜底，覆盖全部 496 个键
 *   3. 主题 _config.yml 里的注释  —— 有则追加（常用于列出可选值）
 *
 * 优先级：GROUP_TIERS 是分层的分组顺序（越靠前越常改），
 * 组内再按 KEY_ORDER 里的键名偏好排序；最终由调用方算成连续序号写入「优先级」列。
 */

/* ─────────────── 分组优先级（按“一个博主多久会改一次”排） ─────────────── */

export const GROUP_TIERS = [
  // ① 站点身份与首页：建站第一件事就是改这些
  ['avatar', 'favicon', 'blog_title_font', 'subtitle', 'social', 'nav', 'menu',
    'home_top', 'index_img', 'default_top_img', 'disable_top_img',
    'index_site_info_top', 'index_top_img_height', 'index_post_content',
    'cover', 'error_img', 'error_404', 'pageThumbnailSuffix',
    'category_ui', 'tag_ui', 'author_status', 'runtimeshow'],

  // ② 页脚 / 侧栏 / 悬浮件：版面骨架
  ['footer', 'footer_bg', 'aside', 'sidebar', 'newest_comments',
    'rightside_item_order', 'rightside-bottom', 'centerConsole',
    'linkPageTop', 'friends_vue', 'greetingBox', 'ptool'],

  // ③ 文章阅读体验：读者看到的东西
  ['post_meta', 'toc', 'post_copyright', 'reward', 'post_edit', 'related_post',
    'photofigcaption', 'post_pagination', 'noticeOutdate', 'sharejs', 'addtoany',
    'wordcount', 'readmode', 'anchor', 'copy', 'h2Divider',
    'table_interlaced_discoloration', 'article_double_row', 'note',
    'dynamicEffect', 'mainTone', 'post_head_ai_description'],

  // ④ 评论与互动
  ['comments', 'valine', 'waline', 'twikoo', 'artalk', 'giscus',
    'comment_barrage_config', 'visitorMail',
    'chat_btn', 'chat_hide_show', 'chatra', 'tidio', 'daovoice', 'crisp'],

  // ⑤ 外观 / 动效 / 交互细节
  ['theme_color', 'darkmode', 'display_mode', 'font', 'beautify', 'preloader',
    'hr_icon', 'icons', 'medium_zoom', 'fancybox', 'snackbar', 'diytitle',
    'rightClickMenu', 'shortcutKey', 'accesskey', 'translate', 'agreementPopup', 'mourn',
    'canvas_ribbon', 'canvas_fluttering_ribbon', 'canvas_nest',
    'activate_power_mode', 'fireworks', 'click_heart', 'ClickShowText',
    'peoplecanvas', 'universe', 'bubble', 'console'],

  // ⑥ 功能模块：搜索 / 统计 / 广告 / 音乐 / 渲染扩展
  ['local_search', 'algolia_search', 'docsearch', 'mermaid', 'katex', 'mathjax',
    'baidu_analytics', 'google_analytics', 'cnzz_analytics', 'cloudflare_analytics',
    'microsoft_clarity', 'umami', 'LA', 'busuanzi', 'google_adsense',
    'nav_music', 'music_page_default', 'aplayerInject',
    'pwa', 'site_verification', 'Open_Graph_meta', 'inject'],

  // ⑦ 性能与底层：改错会影响整站加载，最后看
  ['CDN', 'lazyload', 'pjax', 'pangu', 'instantpage', 'css_prefix',
    'highlight_theme', 'highlight_copy', 'highlight_lang', 'highlight_shrink',
    'highlight_height_limit', 'code_word_wrap'],
];

/** 组内排序：总开关（enable）永远排在该组最前，其余按路径字母序 */
export const ENABLE_FIRST = 'enable';

/** 同一父级下的末级键排序偏好：总开关 → 最常改的字段 → 其余按字母序 */
export const LEAF_ORDER = ['enable', 'use', 'img', 'avatar', 'url', 'link', 'serverURL', 'server',
  'apiurl', 'apiHost', 'name', 'title', 'subtitle', 'sub', 'text', 'description', 'content',
  'mode', 'type', 'style', 'effect', 'field', 'position', 'limit', 'count', 'length',
  'per_page', 'pageSize'];

/* ─────────────── 分组说明（133 个顶层分组全覆盖） ─────────────── */

export const GROUP_DESC = {
  menu: '侧边栏 / 汉堡菜单的菜单项（每一项是「名称: 链接 || 图标」，可分组）',
  nav: '顶部导航栏（是否显示、显示时钟、导航菜单结构）',
  mourn: '哀悼日：指定日期全站变灰（不含滚动条，仅首页生效）',
  highlight_theme: '代码块配色主题',
  highlight_copy: '代码块右上角「复制」按钮',
  highlight_lang: '代码块左上角语言标识',
  highlight_shrink: '代码块默认折叠（点击展开）',
  highlight_height_limit: '代码块最大高度（超过则出滚动条），单位 px',
  code_word_wrap: '代码自动换行（长行不横向滚动）',
  copy: '正文复制行为（复制时追加版权提示、限制字数）',
  social: '社交账号图标（首页头像下方与页脚显示，图标名取自主题图标库）',
  author_status: '作者状态卡：显示一张状态图 + 技能标签',
  algolia_search: 'Algolia 搜索（第三方云搜索，需要 Algolia 账号）',
  docsearch: 'DocSearch 搜索（面向文档站，需要申请 appId/apiKey）',
  local_search: '本地搜索：构建时生成索引，搜索不依赖外部服务',
  mathjax: 'MathJax 数学公式渲染',
  katex: 'KaTeX 数学公式渲染（比 MathJax 更快，符号支持略少）',
  favicon: '浏览器标签页图标（建议 32×32 或 ico/webp）',
  avatar: '站点头像（首页头像、侧栏作者卡都用它）',
  disable_top_img: '全局关闭所有页面顶部图（文章单独配置的仍保留）',
  index_img: '首页顶部图（只影响首页）',
  default_top_img: '默认顶部图：页面/文章没有单独配图时统一用这张',
  cover: '文章封面：首页卡片 / 侧栏 / 归档是否显示封面，以及默认封面图',
  error_img: '图片加载失败时的占位图（友链页与文章页可分别设置）',
  error_404: '404 页面的文案与背景图',
  post_meta: '文章元信息：日期格式、是否显示分类/标签/字数等',
  mainTone: '主色调提取：按封面图自动给文章页换主题色',
  wordcount: '字数统计与预计阅读时长',
  index_post_content: '首页文章列表的摘要规则（自动截断或按 [more] 标记）',
  anchor: '标题锚点（鼠标悬停标题出现 # 可复制直达链接）',
  toc: '文章目录（在文章页与独立页面是否显示、是否自动展开、编号）',
  post_copyright: '文章版权声明（作者、来源地、许可协议、是否禁止转载）',
  reward: '打赏：文章末尾的赞赏二维码/链接',
  post_edit: '「编辑本文」按钮（跳到 GitHub / 语雀对应位置）',
  related_post: '相关文章推荐（按标签或分类匹配）',
  photofigcaption: '图片灯箱里显示图片说明文字（读取 alt）',
  post_pagination: '上一篇 / 下一篇导航按钮',
  noticeOutdate: '文章过期提醒：超过 N 天自动提示内容可能过时',
  sharejs: 'share.js 一键分享按钮',
  addtoany: 'AddToAny 分享按钮（支持更多平台）',
  comments: '评论系统总开关：选默认系统、是否懒加载、是否显示评论数',
  valine: 'Valine 评论系统（LeanCloud 后端）',
  waline: 'Waline 评论系统（可自建服务端）',
  twikoo: 'Twikoo 评论系统（支持云函数部署）',
  artalk: 'Artalk 评论系统（可自建服务端）',
  giscus: 'Giscus 评论系统（基于 GitHub Discussions，无需自建后端）',
  chat_btn: '右下角客服按钮图标',
  chat_hide_show: '滚动时自动隐藏/显示客服按钮',
  chatra: 'Chatra 在线客服',
  tidio: 'Tidio 在线客服',
  daovoice: 'DaoVoice 在线客服',
  crisp: 'Crisp 在线客服',
  footer: '页脚：版权、运行时间、徽章、社交条、备案、链接列表等',
  baidu_analytics: '百度统计（填统计代码里的 key 即可）',
  google_analytics: 'Google Analytics 4',
  cnzz_analytics: 'CNZZ 友盟统计',
  cloudflare_analytics: 'Cloudflare Web Analytics',
  microsoft_clarity: 'Microsoft Clarity 行为分析（录屏/热图）',
  google_adsense: 'Google AdSense 广告位',
  site_verification: '站长平台验证（把各平台给出的验证码填进来，用于提交收录）',
  theme_color: '主题色：主色、深色模式主色、分页器、文字选中等配色',
  sidebar: '侧栏用户中心：归档/标签/分类数量、导航项、标签云等',
  h2Divider: '二级标题下方显示分隔线',
  table_interlaced_discoloration: '表格隔行变色，长表格更易读',
  article_double_row: '文章双栏排版（大屏下左右两栏）',
  index_site_info_top: '首页站点信息区距页面顶部的距离（如 300px）',
  index_top_img_height: '首页顶部图高度（默认全屏，可写 100vh 或 300px）',
  category_ui: '分类页卡片 UI 样式',
  tag_ui: '标签页卡片 UI 样式',
  footer_bg: '页脚背景图',
  'rightside-bottom': '右下角悬浮按钮距页面底部的距离',
  canvas_ribbon: '彩带飘动背景动效',
  canvas_fluttering_ribbon: '飘带飘动背景动效（更飘逸的版本）',
  canvas_nest: '蛛网/粒子连线背景动效',
  activate_power_mode: '写轮眼模式：按下快捷键后页面抖动 + 彩色化（彩蛋动效）',
  fireworks: '鼠标点击放烟花（彩蛋动效）',
  click_heart: '鼠标点击冒出爱心（彩蛋动效）',
  ClickShowText: '鼠标点击显示自定义文字',
  display_mode: '默认显示模式：白天 / 黑夜 / 跟随系统',
  beautify: '浏览器标签与标题美化（切换标签时显示自定义前缀）',
  font: '全站字体大小与字体族（正文、代码分别设置）',
  blog_title_font: '首页博客大标题的字体（支持引入外部字体）',
  hr_icon: '分割线显示图标（--- 会渲染成带图标的装饰线）',
  subtitle: '首页打字机副标题（循环播放的一组文案）',
  preloader: '进入网站时的加载动画',
  aside: '侧栏卡片：作者卡、公告、最近文章、分类、标签、网站信息等',
  busuanzi: '不蒜子统计：站点访问量 / 访客数 / 单页阅读量',
  runtimeshow: '站点运行时间（页脚显示「已运行 XX 天」）',
  newest_comments: '最新评论卡片（拉取各评论系统的最新评论）',
  translate: '页面翻译（右键菜单或按钮调用翻译服务）',
  readmode: '阅读模式开关（右下角按钮，进入后弱化干扰）',
  centerConsole: '中控台：右下角面板，聚合标签卡、音乐、快捷键等',
  darkmode: '深色模式：开关按钮与自动切换时间区间',
  rightside_item_order: '右下角悬浮按钮的显示/隐藏与排列顺序',
  medium_zoom: 'Medium Zoom：点击图片以缩放动画放大',
  fancybox: 'Fancybox：点击图片以灯箱方式浏览（支持相册）',
  mermaid: 'Mermaid 图表渲染（流程图、时序图等）',
  note: '提示块样式（tip/warning/danger 的图标、圆角、边框）',
  icons: '图标库资源：图标字体与 FontAwesome 的加载地址',
  pjax: 'Pjax 无刷新跳转（页面切换更快，个别脚本需排除）',
  aplayerInject: 'APlayer 全局音乐播放器（文章内注入）',
  snackbar: '右下角消息条与页脚下拉按钮的位置与配色',
  instantpage: 'Instant.Page 预加载：鼠标悬停链接时提前加载目标页',
  pangu: '中英文之间自动加空格（盘古之白）',
  lazyload: '图片懒加载：滚动到可视区才加载',
  pwa: 'PWA 离线应用：可安装到桌面、离线访问',
  Open_Graph_meta: 'OG 元信息（分享到社交平台时的标题/图片/描述）',
  css_prefix: 'CSS 前缀兼容处理',
  home_top: '首页顶部横幅：时间问候、欢迎语、站点文字轮播',
  friends_vue: '友链页（Vue 版）：拉取友链数据、顶部提示与背景',
  universe: '星空背景动效',
  bubble: '气泡背景动效',
  console: '控制台彩蛋（打开 F12 显示自定义信息）',
  LA: '51LA 网站统计',
  umami: 'Umami 自建统计',
  diytitle: '离开页面时把标签标题改成自定义文案（如「别走呀~」）',
  comment_barrage_config: '评论弹幕：把评论以弹幕形式飘过',
  nav_music: '导航栏音乐播放器（网易云歌单）',
  music_page_default: '音乐馆页面默认播放的歌单 ID',
  visitorMail: '访客邮件通知：新评论时给你发邮件',
  ptool: '文章工具：分享菜单、分类快捷入口',
  greetingBox: '问候语弹窗（按时间段显示不同问候）',
  post_head_ai_description: 'AI 摘要：文章顶部自动生成的一句话摘要',
  shortcutKey: '键盘快捷键（组合键触发中控台、搜索等）',
  accesskey: '浏览器访问键（Alt+字母 快速跳转）',
  linkPageTop: '友链页顶部文案与「添加友链」占位提示',
  pageThumbnailSuffix: '封面缩略图后缀：按文件名 + 后缀取缩略图，减少首屏体积',
  agreementPopup: '隐私协议弹窗（首次访问时弹出，可跳转协议页）',
  rightClickMenu: '自定义右键菜单',
  peoplecanvas: '人物立绘动画（用一张图做飘动效果）',
  dynamicEffect: '文章顶图动效与评论滚动动效',
  inject: '注入自定义代码（head / 底部），用于加统计、验证或样式',
  CDN: '静态资源 CDN：主题 js/css 与第三方库的加载来源',
};

/* ─────────────── 重点键的人工词条（优先于组装式说明） ─────────────── */

export const KEY_DESC = {
  // —— 站点身份 ——
  'favicon': '浏览器标签页图标。留空用主题默认；建议放自己的 logo（ico 或 32×32 png/webp）',
  'avatar.img': '站点头像图片地址。首页头像框、侧栏作者卡、评论框都会用它',
  'avatar.effect': '头像鼠标悬停时的效果（true = 旋转）',
  'blog_title_font.font-family': '首页博客大标题的字体名（需与 font_link 引入的字体一致）',
  'blog_title_font.font_link': '首页博客大标题字体的 CSS 引入地址（如 Google Fonts 或自家字体）',
  'subtitle.enable': '首页打字机副标题总开关',
  'subtitle.sub': '打字机轮播的文案列表（一行一条，循环播放）',
  'subtitle.loop': '文案播完后是否从头循环',
  'subtitle.source': '打字机底层库来源（0 = 本地内置，1 = 走 CDN）',
  'subtitle.effect': '打字机文案的播放方式：打字 / 擦除 / 只打字不擦除',
  'subtitle.startDelay': '打字机开始前的等待毫秒数',
  'subtitle.typeSpeed': '每个字的键入速度（毫秒，越小越快）',
  'subtitle.backSpeed': '擦除速度（毫秒）',
  'social': '社交图标列表。格式「图标名: 链接 || 图标类名」，图标名见主题图标库',

  // —— 首页与导航 ——
  'nav.enable': '显示顶部导航栏（关闭后只留侧边汉堡菜单）',
  'nav.travelling': '导航栏显示「旅行」状态（按地理位置变化）',
  'nav.clock': '导航栏显示实时时钟',
  'nav.menu': '导航栏菜单项（分组 + 子项，含链接与图标）',
  'home_top.enable': '首页顶部显示时间问候 / 站点文字轮播横幅',
  'home_top.timemode': '按时间段显示不同问候语（0 点开始算）',
  'home_top.title': '横幅主标题',
  'home_top.subTitle': '横幅副标题',
  'home_top.category': '横幅的时间问候语配置（按时间段分组）',
  'home_top.default_descr': '未命中任何时间段时显示的问候语',
  'home_top.siteText': '横幅下方轮播的站点文字（一行一条）',
  'menu': '侧边栏与汉堡菜单的菜单项（格式「名称: 链接 || 图标」，可分组嵌套）',
  'index_img': '首页顶部图。留空则用 default_top_img',
  'default_top_img': '默认顶部图。所有没单独配图的页面/文章共用它；留空则不显示顶部图',
  'index_site_info_top': '首页站点信息（头像/标题/描述）距页面顶部的距离',
  'index_top_img_height': '首页顶部图高度。默认全屏，可写 100vh 或 300px 等',
  'index_post_content.method': '首页摘要方式：1 = 自动截断，2 = 优先取 [more] 标记，3 = 只显示 [more] 前内容',
  'index_post_content.length': '自动截断的字数上限',
  'pageThumbnailSuffix': '封面缩略图后缀。设为 -thumbnail 后，封面 xxx.webp 会自动改用 xxx-thumbnail.webp 做缩略图',
  'cover.index_enable': '首页文章卡片是否显示封面图',
  'cover.aside_enable': '侧栏最新文章卡片是否显示封面缩略图',
  'cover.archives_enable': '归档页文章列表是否显示封面',
  'cover.position': '封面主体位置：left / center / right（决定裁切时保留哪一侧）',
  'cover.default_cover': '默认封面图列表。文章没配封面时按顺序轮换使用；留空则用主题自带默认图',
  'error_img.post_page': '文章内容里的图片加载失败时显示的占位图',
  'error_img.flink': '友链页头像加载失败时显示的占位图',
  'error_404.enable': '自定义 404 页面',
  'error_404.subtitle': '404 页面副标题文案',
  'error_404.background': '404 页面背景图',
  'author_status.enable': '侧栏显示作者状态卡（一张状态图 + 技能标签）',
  'author_status.statusImg': '作者状态卡顶部图片地址',
  'author_status.skills': '作者状态卡的技能标签列表',
  'runtimeshow.enable': '页脚显示「本站已运行 XX 天」',
  'runtimeshow.publish_date': '站点上线日期，用于计算运行天数（格式 YYYY-MM-DD）',

  // —— 页脚 ——
  'footer.owner.enable': '页脚显示版权信息',
  'footer.owner.since': '版权起始年份（显示为 © 2019 - 2026）',
  'footer.custom_text': '页脚自定义文案（支持 HTML）',
  'footer.runtime.enable': '页脚显示「搬砖中 / 摸鱼中」状态',
  'footer.runtime.launch_time': '工作状态计算的时间基准（格式 YYYY-MM-DDTHH:mm:ss）',
  'footer.bdageitem.enable': '页脚显示徽章（Hexo、GitHub 等 shields 徽章）',
  'footer.bdageitem.list': '徽章列表（名称 + shields 地址 + 点击链接）',
  'footer.socialBar.enable': '页脚显示社交条',
  'footer.socialBar.left': '页脚社交条左侧按钮（标题 + 链接 + 图标）',
  'footer.socialBar.right': '页脚社交条右侧按钮',
  'footer.list.enable': '页脚显示链接列表（服务 / 支持 等多列链接）',
  'footer.list.project': '页脚链接列表内容（每列一组：标题 + 链接数组）',
  'footer.footerBar.cc.enable': '页脚显示 CC 版权协议图标',
  'footer.footerBar.cc.link': 'CC 协议说明页链接',
  'footer.footerBar.linkList': '页脚最底部的链接（隐私协议、站点地图等）',
  'footer_bg': '页脚背景图地址（留空用纯色）',

  // —— 侧栏 ——
  'aside.enable': '显示侧栏（移动端会自动收起，可用 aside.hide 强制隐藏）',
  'aside.hide': '强制隐藏整个侧栏（桌面端也不显示）',
  'aside.button': '侧栏收起/展开按钮的颜色',
  'aside.mobile': '移动端是否显示侧栏',
  'aside.position': '侧栏在左还是在右',
  'aside.card_author.enable': '侧栏「作者卡」',
  'aside.card_author.description': '作者卡里的自我介绍（支持 HTML）',
  'aside.card_announcement.enable': '侧栏「公告」卡片',
  'aside.card_announcement.content': '公告内容',
  'aside.card_recent_post.enable': '侧栏「最近文章」卡片',
  'aside.card_recent_post.limit': '最近文章显示条数',
  'aside.card_newest_comment.enable': '侧栏「最新评论」卡片',
  'aside.card_weixin.enable': '侧栏「微信」卡片（悬停展示二维码）',
  'aside.card_weixin.face': '微信卡片正面图片',
  'aside.card_weixin.backFace': '微信卡片悬停后显示的二维码图',
  'aside.card_webinfo.enable': '侧栏「网站信息」卡片（文章数、标签数、访问量等）',
  'aside.card_tags.enable': '侧栏「标签」卡片',
  'aside.card_categories.enable': '侧栏「分类」卡片',
  'aside.card_archives.enable': '侧栏「归档」卡片',
  'newest_comments.enable': '侧栏最新评论卡片总开关',
  'newest_comments.limit': '最新评论显示条数',
  'newest_comments.sort_order': '最新评论排序方式（newest 最新优先）',
  'newest_comments.storage': '评论数据来源（选择你实际在用的评论系统）',
  'rightside_item_order.enable': '自定义右下角悬浮按钮的顺序',
  'rightside_item_order.hide': '隐藏某些悬浮按钮（填按钮名）',
  'rightside_item_order.show': '显示被主题默认隐藏的悬浮按钮',
  'centerConsole.enable': '右下角「中控台」面板（聚合标签、音乐、快捷键等）',
  'linkPageTop.enable': '友链页顶部横幅',
  'linkPageTop.title': '友链页顶部标题',
  'linkPageTop.addFriendPlaceholder': '「添加友链」按钮的提示文案',
  'friends_vue.enable': '使用 Vue 版友链页（数据来自接口或静态 JSON）',
  'friends_vue.apiurl': '友链数据接口地址',
  'greetingBox.enable': '首次访问弹出问候语',
  'greetingBox.default': '默认问候语（未命中时间段时使用）',
  'ptool.enable': '文章右下角工具（分享菜单、分类快捷入口）',
  'ptool.categories': '文章工具里显示的分类快捷入口',

  // —— 文章页 ——
  'post_meta.page.date_type': '列表页日期显示方式（created / updated）',
  'post_meta.page.date_format': '列表页日期格式（date 完整 / relative 相对时间）',
  'post_meta.page.categories': '列表页显示分类',
  'post_meta.page.tags': '列表页显示标签',
  'post_meta.post.date_type': '文章页日期显示方式（created / updated / both）',
  'post_meta.post.date_format': '文章页日期格式（date / relative）',
  'post_meta.post.categories': '文章页显示分类',
  'post_meta.post.tags': '文章页显示标签',
  'post_meta.post.unread': '文章页显示阅读进度条',
  'toc.post': '文章页显示目录',
  'toc.page': '独立页面（关于、友链等）显示目录',
  'toc.number': '目录自动编号',
  'toc.expand': '目录默认展开（不折叠）',
  'toc.style_simple': '目录使用简洁样式',
  'post_copyright.enable': '文章底部显示版权声明',
  'post_copyright.decode': '加密文章是否启用版权声明',
  'post_copyright.author_href': '版权声明里作者名的跳转链接',
  'post_copyright.location': '作者所在地（显示在版权信息里）',
  'post_copyright.license': '采用的许可协议名称',
  'reward.enable': '文章底部显示打赏按钮',
  'reward.QR_code': '打赏二维码列表（图片 + 说明文字）',
  'post_edit.enable': '文章页显示「编辑本文」按钮',
  'post_edit.github': 'GitHub 编辑入口（用户名/仓库/分支）',
  'post_edit.yuque': '语雀编辑入口',
  'related_post.enable': '文章底部显示相关文章推荐',
  'related_post.limit': '相关文章显示条数',
  'related_post.date_type': '相关文章匹配方式（created 同标签 / updated 同分类）',
  'photofigcaption': '图片灯箱显示说明文字（读取图片 alt）',
  'post_pagination': '上一篇 / 下一篇按钮的样式（1 = 文字，2 = 带标题卡片）',
  'noticeOutdate.enable': '文章超过指定天数时显示过期提醒',
  'noticeOutdate.style': '过期提醒样式（flat 简洁 / simple 简约）',
  'noticeOutdate.limit_day': '超过多少天提示内容可能过时',
  'noticeOutdate.position': '提醒显示在文章顶部还是底部',
  'noticeOutdate.message_prev': '提醒文案前半段（会接上「N 天前」）',
  'noticeOutdate.message_next': '提醒文案后半段',
  'sharejs.enable': '开启 share.js 一键分享',
  'sharejs.sites': '参与分享的平台列表',
  'addtoany.enable': '开启 AddToAny 分享（平台更多）',
  'addtoany.item': 'AddToAny 显示的分享按钮',
  'wordcount.enable': '显示字数统计与预计阅读时长',
  'wordcount.post_wordcount': '文章页显示字数',
  'wordcount.min2read': '显示预计阅读分钟数',
  'wordcount.total_wordcount': '侧栏显示全站总字数',
  'readmode': '右下角显示「阅读模式」按钮',
  'anchor': '标题悬停显示 # 锚点，可复制直达链接',
  'h2Divider': '二级标题下方显示分隔线',
  'table_interlaced_discoloration': '表格隔行变色',
  'article_double_row': '文章双栏排版（大屏下生效）',
  'note.style': '提示块默认样式（simple / modern）',
  'note.icons': '提示块显示图标',
  'note.border_radius': '提示块圆角大小',
  'mainTone.enable': '按封面图自动提取主色调并应用到文章页',
  'mainTone.mode': '取色方式：colorthief（前端取色）/ cdn（图片地址带参数）/ api（请求取色接口）/ both（先 cdn 后 api）',
  'mainTone.api': '取色接口地址（mode 为 api 或 both 时使用）',
  'mainTone.cover_change': '封面变化时同步更新主色调',
  'dynamicEffect.postTopWave': '文章顶部图波浪动效',
  'dynamicEffect.postTopRollZoomInfo': '文章顶部信息滚动放大动效',
  'dynamicEffect.pageCommentsRollZoom': '评论滚动放大动效',
  'post_head_ai_description.enable': '在文章顶部显示 AI 生成的一句话摘要',
  'post_head_ai_description.gptName': '摘要区显示的名称（如「AI 摘要」）',
  'post_head_ai_description.mode': '摘要来源：ai 自动生成 / 手动填写',
  'post_head_ai_description.switchBtn': '显示开关按钮，可折叠摘要',
  'copy.enable': '代码块与正文的复制功能',
  'copy.copyright.enable': '复制正文时自动追加版权说明',
  'copy.copyright.limit_count': '超过多少字才追加版权说明',

  // —— 评论 ——
  'comments.use': '默认评论系统（同时只能用一个作为默认，如 Waline）',
  'comments.text': '评论区顶部文案',
  'comments.lazyload': '评论懒加载（滚动到评论区才加载）',
  'comments.count': '显示每篇文章的评论数',
  'comments.card_post_count': '侧栏文章卡片显示评论数',
  'waline.serverURL': 'Waline 服务端地址（自建或官方 Vercel 部署地址）',
  'waline.bg': '评论区背景图',
  'waline.pageview': '启用 Waline 阅读量统计',
  'waline.imageUploader': '是否允许在评论里上传图片',
  'twikoo.envId': 'Twikoo 环境地址（云函数 / 自建服务地址）',
  'twikoo.region': 'Twikoo 部署区域（自建时填写）',
  'valine.appId': 'Valine 的 LeanCloud AppID',
  'valine.appKey': 'Valine 的 LeanCloud AppKey（密钥，勿外泄）',
  'giscus.repo': 'Giscus 使用的 GitHub 仓库（格式 owner/repo）',
  'giscus.repo_id': 'Giscus 仓库 ID（在 giscus.app 生成）',
  'giscus.category_id': 'Giscus 讨论分类 ID（在 giscus.app 生成）',
  'artalk.server': 'Artalk 服务端地址',
  'artalk.site': 'Artalk 站点名（多站点复用一个服务端时区分）',
  'comment_barrage_config.enable': '把评论变成弹幕飘过',
  'visitorMail.enable': '有新评论时给自己发邮件提醒',
  'visitorMail.mail': '接收提醒的邮箱',

  // —— 外观 ——
  'theme_color.enable': '启用自定义主题色（关闭则用主题自带配色）',
  'theme_color.main': '白天模式主色',
  'theme_color.dark_main': '深色模式主色',
  'darkmode.enable': '显示深色模式切换按钮',
  'darkmode.button': '深色模式下按钮配色',
  'darkmode.autoChangeMode': '按时段自动切换 (1 = 跟随系统，2 = 按时间，3 = 两者结合)',
  'darkmode.start': '自动进入深色模式的起始时间（小时，0-24）',
  'darkmode.end': '自动退出深色模式的时间（小时，0-24）',
  'display_mode': '首次访问的默认显示模式',
  'font.global-font-size': '正文字号（如 16px）',
  'font.code-font-size': '代码字号',
  'font.font-family': '正文字体族（内置可选项，也可写自定义字体名）',
  'font.code-font-family': '代码字体族',
  'beautify.enable': '浏览器标签与标题美化（切换标签时显示自定义前缀）',
  'beautify.title-prefix-icon': '标题前缀图标',
  'preloader.enable': '进入网站时显示加载动画',
  'preloader.source': '加载动画使用的图标集（1 = 主题内置，2 = 第三方 pace）',
  'preloader.avatar': '加载动画里显示的头像',
  'medium_zoom': '点击图片以缩放动画放大（与 fancybox 二选一）',
  'fancybox': '点击图片以灯箱方式浏览（支持左右切换相册）',
  'snackbar.enable': '右下角消息条与页脚下拉按钮',
  'diytitle.enable': '离开页面时修改标签标题（如「别走呀~」）',
  'diytitle.leaveTitle': '离开时显示的标题',
  'diytitle.backTitle': '回来时显示的标题',
  'translate.enable': '开启页面翻译功能',
  'translate.default': '默认翻译目标语言',
  'agreementPopup.enable': '首次访问弹出隐私协议',
  'agreementPopup.url': '协议全文链接',
  'mourn.enable': '哀悼日全站变灰',
  'mourn.days': '需要变灰的日期列表（MM-DD）',
  'icons.ali_iconfont_js': '阿里图标字体 JS 地址（主题图标库来源）',
  'icons.fontawesome': 'FontAwesome 图标库地址',
  'shortcutKey.enable': '键盘快捷键（组合键打开中控台、搜索等）',
  'accesskey.enable': '浏览器访问键（Alt + 字母快速跳转）',
  'rightClickMenu.enable': '自定义右键菜单',

  // —— 功能模块 ——
  'local_search.enable': '开启本地搜索（构建时生成索引，不依赖外部服务）',
  'local_search.preload': '预加载搜索索引（首屏更快，但会增大流量）',
  'algolia_search.enable': '开启 Algolia 云搜索',
  'docsearch.enable': '开启 DocSearch 搜索',
  'mermaid.enable': '渲染 Mermaid 图表（流程图、时序图等）',
  'katex.enable': '渲染 KaTeX 数学公式',
  'mathjax.enable': '渲染 MathJax 数学公式（与 katex 二选一）',
  'baidu_analytics': '百度统计 key（统计代码里 hm.js? 后面那串）',
  'google_analytics': 'Google Analytics 衡量 ID（G-XXXXXXXX）',
  'cnzz_analytics': 'CNZZ / 友盟统计 ID',
  'cloudflare_analytics': 'Cloudflare Web Analytics 的 token',
  'microsoft_clarity': 'Microsoft Clarity 项目 ID',
  'umami.enable': '开启 Umami 自建统计',
  'umami.apiHost': 'Umami 服务地址',
  'umami.websiteId': 'Umami 站点 ID',
  'LA.enable': '开启 51LA 统计',
  'LA.ck': '51LA 的 ck 参数',
  'busuanzi.site_uv': '侧栏显示站点访客数',
  'busuanzi.site_pv': '侧栏显示站点访问量',
  'busuanzi.page_pv': '文章页显示本页阅读量',
  'google_adsense.enable': '开启 Google AdSense 广告',
  'google_adsense.client': 'AdSense 客户端 ID（ca-pub-xxxx）',
  'google_adsense.auto_ads': '开启自动广告',
  'nav_music.enable': '导航栏显示音乐播放器',
  'nav_music.id': '网易云歌单 ID',
  'nav_music.server': '音乐接口服务地址（主题自带的公共接口）',
  'nav_music.volume': '默认音量（0-1）',
  'music_page_default': '音乐馆页面默认播放的歌单 ID',
  'aplayerInject.enable': '开启全局音乐播放器注入',
  'pwa.enable': '开启 PWA（可安装到桌面、离线访问）',
  'pwa.manifest': 'PWA 清单配置（名称、图标、主题色等）',
  'site_verification.enable': '是否输出站长验证 meta（一般保持 true）',
  'Open_Graph_meta': '输出 OG 元信息（分享到社交平台的标题/图/描述）',
  'inject.head': '注入到 <head> 的自定义代码（统计、验证、样式）',
  'inject.bottom': '注入到页面底部的自定义代码（脚本）',

  // —— 性能 / 底层 ——
  'CDN.internal_provider': '主题内置资源（js/css）的 CDN 来源',
  'CDN.third_party_provider': '第三方库的 CDN 来源',
  'CDN.version': '主题资源版本号（一般不要改）',
  'CDN.custom_format': '自定义 CDN 路径格式（换用自建 CDN 时使用）',
  'lazyload.enable': '图片懒加载（滚动到可视区才加载，省流量）',
  'lazyload.field': '懒加载生效范围（DOM 选择器）',
  'lazyload.placeholder': '懒加载占位图地址',
  'lazyload.blur': '开启图片渐进式清晰（模糊到清晰）',
  'pjax.enable': 'Pjax 无刷新跳转（页面切换更快）',
  'pjax.exclude': '不参与 Pjax 的页面/脚本（正则，用 | 分隔）',
  'pangu.enable': '中英文之间自动插入空格（盘古之白）',
  'pangu.field': '盘古之白生效范围（DOM 选择器）',
  'instantpage': 'Instant.Page 预加载（鼠标悬停链接时提前加载）',
  'css_prefix': 'CSS 类名前缀（多主题共存时用，单站保持 true）',
  'highlight_theme': '代码块配色主题（light / mac / ocean / dark 等，false = 不配色）',
  'highlight_shrink': '代码块默认折叠',
  'highlight_height_limit': '代码块最大高度（px，超过出滚动条）',
  'code_word_wrap': '代码自动换行',
};

/* ─────────────── 末级键名的通用语义（组装式说明用） ─────────────── */

export const LEAF_DESC = {
  enable: '是否启用',
  use: '使用哪个（填名称）',
  mode: '模式选择',
  type: '类型选择',
  style: '样式选择',
  effect: '效果选择',
  img: '图片地址',
  avatar: '头像地址',
  url: '链接地址',
  link: '链接地址',
  serverURL: '服务端地址',
  server: '服务端地址',
  apiurl: '接口地址',
  apiHost: '接口地址',
  id: '标识 ID',
  appId: '应用 ID',
  app_id: '应用 ID',
  appKey: '密钥（勿外泄）',
  apiKey: '密钥（勿外泄）',
  public_key: '公钥',
  website_id: '站点 ID',
  envId: '环境 ID / 地址',
  client: '客户端 ID',
  token: '访问令牌（勿外泄）',
  ck: '统计标识',
  secret: '密钥（勿外泄）',
  name: '名称',
  title: '标题文案',
  subtitle: '副标题文案',
  text: '文案内容',
  description: '描述文案',
  content: '内容',
  field: '生效范围（DOM 选择器）',
  position: '位置',
  limit: '数量上限',
  count: '数量',
  length: '长度',
  per_page: '每页数量',
  pageSize: '每页数量',
  color: '颜色值',
  bg: '背景（图片地址或颜色）',
  bg_light: '白天模式配色',
  bg_dark: '深色模式配色',
  size: '尺寸',
  fontSize: '字号',
  height: '高度',
  days: '日期列表',
  mobile: '移动端是否启用',
  zIndex: '层级（越大越靠前）',
  option: '高级参数（透传给该服务的初始化对象）',
  list: '列表内容',
  i18n: '多语言配置',
};
